name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1


name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate mocks
      run: go generate ./...

    - name: Run tests
      run: go test ./... -v
      env:
        THOLA_TEST_SIMPLEUI: true
        
    - name: Staticcheck 
      uses: dominikh/staticcheck-action@v1.0.0
      with:
        version: "2021.1.1"
